### ISSUE TITLE
I have written a tproxy listener socket, can you add this function to your proxy?

### ISSUE THREAD

**Issue by elico** [ryanchapman/go-any-proxy#19]
My code is at:
http://paste.ngtech.co.il/plseujxih

It's basically a sketch rather then full implementation since it doesn't have the tproxy dial bind option.
I have seen a tproxy outgoing connection example at:
https://github.com/andrew-d/demux/blob/master/transparent_linux.go
I will later write my own code that will use it.
Is it any of interest for you?

**Comment by ryanchapman** [comment]
Hi,

Looks interesting.  I don't have a ton of time to pull it into any-proxy--buried in radius server code for now. Feel free to send me a pull request if you are wanting to integrate it into any_proxy (just be sure to put the command line opts code in there too).

Best,
Ryan
