### ISSUE TITLE
i installed any_proxy ,failed,how to fix it?

### ISSUE THREAD

**Issue by luckypoem** [ryanchapman/go-any-proxy#24]
hi.

root@ar:~/go/gopath# go get -u -v github.com/ryanchapman/go-any-proxy
github.com/ryanchapman/go-any-proxy (download)
github.com/namsral/flag (download)
github.com/zdannar/flogger (download)
github.com/namsral/flag
github.com/zdannar/flogger
github.com/ryanchapman/go-any-proxy
# github.com/ryanchapman/go-any-proxy
src/github.com/ryanchapman/go-any-proxy/any_proxy.go:200:51: undefined: BUILDTIMESTAMP
src/github.com/ryanchapman/go-any-proxy/any_proxy.go:201:28: undefined: BUILDTIMESTAMP
src/github.com/ryanchapman/go-any-proxy/any_proxy.go:202:91: undefined: BUILDUSER
src/github.com/ryanchapman/go-any-proxy/any_proxy.go:202:102: undefined: BUILDHOST
root@ar:~/go/gopath# which any_proxy
root@ar:~/go/gopath#

**Comment by ryanchapman** [comment]
Hi,

Thanks for the report.
I added installation instructions at https://github.com/ryanchapman/go-any-proxy#installation

Ryan

**Comment by ryanchapman** [comment]
I'm going to close this for now.  Let me know if you have further questions.

Ryan
